name: Deploy to Azure Container Instances using Docker Hub

on:
  push:
    branches: [new-feature/Carlos]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/nextjs-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group medusa \
            --name nextjs-app \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-app:${{ github.sha }} \
            --registry-username ${{ secrets.DOCKERHUB_USERNAME }} \
            --registry-password ${{ secrets.DOCKERHUB_PASSWORD }} \
            --dns-name-label nextjs-app-label-${{ github.run_number }} \
            --ports 3000 \
            --location eastus \
            --restart-policy Never
